name: Build on push
on: 
  push:
    branches: 
      - master
    path-ignore:
      - ".github/**"
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: |
          yarn
          yarn build
          npx netlify-cli deploy --dir=public --prod